apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  APP_USERNAME: YWRtaW4=   # "admin" base64
  APP_PASSWORD: cGFzc3dvcmQ=   # "password" base64
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
  - name: demo
    image: busybox
    command: [ "sh", "-c", "env | grep APP_" ]
    env:
    - name: APP_USERNAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: APP_USERNAME
    - name: APP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: APP_PASSWORD
