apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
    <head><title>Custom Nginx</title></head>
    <body>
      <h1>Hello from ConfigMap!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-html
    configMap:
      name: nginx-config
      items:
      - key: index.html
        path: index.html
